lab12/lab2.2/Models/CalcModel.cs
namespace lab2._2.Models
{
    public class CalcModel
    {
        public int x { get; set; }
        public int y { get; set; }
        public string Operation { get; set; }

        public string Calc()
        {
            return Operation switch
            {
                "+" => $"{x} + {y} = {x + y}",
                "-" => $"{x} - {y} = {x - y}",
                "*" => $"{x} * {y} = {x * y}",
                "/" => y != 0 ? $"{x} /  {y} = {x / y}" : "Division by zero",
                _ => "Invalid operation"
            };
        }
    }
}

lab12/lab2.2/Models/ErrorViewModel.cs
namespace lab2._2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

lab12/lab2.2/Controllers/CalcController.cs
using lab2._2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace lab2._2.Controllers
{
    public class CalcController : Controller
    {
        private readonly ILogger<CalcController> _logger;

        public CalcController(ILogger<CalcController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult Manual()
        {
            if (Request.Method == "POST")
            {
                try
                {
                    var calcModel = new CalcModel
                    {
                        x = Int32.Parse(HttpContext.Request.Form["x"]),
                        Operation = HttpContext.Request.Form["operation"],
                        y = Int32.Parse(HttpContext.Request.Form["y"])
                    };

                    ViewBag.Result = calcModel.Calc();
                }
                catch
                {
                    ViewBag.Result = "Invalid input";
                }

                return View("Result");
            }
            return View("ViewWithHtmlHelpers");
        }

        [HttpGet]
        [ActionName("ManualWithSeparateHandlers")]
        public IActionResult ManualWithSeparateHandlersGet()
        {
            return View("ViewWithHtmlHelpers");
        }

        [HttpPost]
        [ActionName("ManualWithSeparateHandlers")]
        public IActionResult ManualWithSeparateHandlersPost()
        {
            try
            {
                var calcModel = new CalcModel
                {
                    x = Int32.Parse(HttpContext.Request.Form["x"]),
                    Operation = HttpContext.Request.Form["operation"],
                    y = Int32.Parse(HttpContext.Request.Form["y"])
                };

                ViewBag.Result = calcModel.Calc();
            }
            catch
            {
                ViewBag.Result = "Invalid input";
            }

            return View("Result");
        }

        [HttpGet]
        public IActionResult ModelBindingInParameters()
        {
            return View("ViewWithHtmlHelpers");
        }

        [HttpPost]
        public IActionResult ModelBindingInParameters(int x, string operation, int y)
        {
            if (ModelState.IsValid)
            {
                var calcModel = new CalcModel
                {
                    x = x,
                    Operation = operation,
                    y = y
                };
                ViewBag.Result = calcModel.Calc();
            }
            else
            {
                ViewBag.Result = "Invalid input";
            }

            return View("Result");
        }

        [HttpGet]
        public IActionResult ModelBindingInSeparateModel()
        {
            return View("ViewWithTagHelpers");
        }

        [HttpPost]
        public IActionResult ModelBindingInSeparateModel(CalcModel model)
        {
            ViewBag.Result = ModelState.IsValid
                ? model.Calc()
                : "Invalid input";

            return View("Result");
        }
    }
}

lab12/lab2.2/Controllers/HomeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace lab2._2.Controllers
{
    public class HomeController : Controller
    {
        // GET: HomeController
        public ActionResult Index()
        {
            return View();
        }

        // GET: HomeController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: HomeController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: HomeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: HomeController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: HomeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: HomeController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: HomeController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

lab12/lab2.2/Views/Calc/Result.cshtml
@{
    ViewBag.Title = "Result";
}
<h1>Result</h1>
@ViewBag.Result

lab12/lab2.2/Views/Calc/ViewWithHtmlHelpers.cshtml
@{
    var action = ViewContext.RouteData.Values["Action"] as string;
    var controller = ViewContext.RouteData.Values["Controller"] as string;
    ViewBag.Title = action;
}
<h1>@action</h1>

@using (Html.BeginForm(action, controller, FormMethod.Post))
{
    @Html.TextBox("x", "")
    <br />
    @Html.DropDownList("operation", new SelectList(new[] { "+", "-", "*", "/" }))
    <br />
    @Html.TextBox("y", "")
    <br />
    <input type="submit" value="Submit" />
}

lab12/lab2.2/Views/Calc/ViewWithTagHelpers.cshtml
@model lab2._2.Models.CalcModel
@{
    var action = ViewContext.RouteData.Values["Action"] as string;
    ViewBag.Title = action;
    var operations = new SelectList(new[] { "+", "-", "*", "/" });
}
<h1>@action</h1>

<form asp-controller="Calc" asp-action="@action">
    <input asp-for="x" /><br />
    <select asp-for="Operation" asp-items="operations"></select><br />
    <input asp-for="y" /><br />
    <input type="submit" value="Submit" />
</form>

lab12/lab2.2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h1>Form parameters parsing demo</h1>
<ul>
    <li><a asp-controller="Calc" asp-action="Manual">Manual parsing in single action</a></li>
    <li><a asp-controller="Calc" asp-action="ManualWithSeparateHandlers">Manual parsing in separate action</a></li>
    <li><a asp-controller="Calc" asp-action="ModelBindingInParameters">Model binding (parameters)</a></li>
    <li><a asp-controller="Calc" asp-action="ModelBindingInSeparateModel">Model binding (separate model)</a></li>
</ul>

lab12/lab2.2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - lab2._2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lab2._2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">lab2._2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - lab2._2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>